name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: 'recursive'

    - name: build
      run: |
        sudo apt-get install -y build-essential cmake vim libevent-dev tar git python net-tools
        git clone https://github.com/google/boringssl.git ./third_party/boringssl
        cd ./third_party/boringssl
        mkdir -p build
        cd build
        cmake -DBUILD_SHARED_LIBS=0 -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" ..
        make ssl crypto
        cd ..
        SSL_TYPE_STR="boringssl"
        SSL_PATH_STR="${PWD}"
        SSL_INC_PATH_STR="${PWD}/include"
        SSL_LIB_PATH_STR="${PWD}/build/ssl/libssl.a;${PWD}/build/crypto/libcrypto.a"
        cd ../..
        git submodule update --init --recursive
        mkdir -p build
        cd build
        cmake -DGCOV=on -DCMAKE_BUILD_TYPE=Debug -DXQC_ENABLE_TESTING=1 -DXQC_SUPPORT_SENDMMSG_BUILD=1 -DXQC_ENABLE_EVENT_LOG=1 -DXQC_ENABLE_BBR2=1 -DXQC_DISABLE_RENO=0 -DSSL_TYPE=${SSL_TYPE_STR} -DSSL_PATH=${SSL_PATH_STR} -DSSL_INC_PATH=${SSL_INC_PATH_STR} -DSSL_LIB_PATH=${SSL_LIB_PATH_STR} ..
        make -j
